# Generated by Django 4.1.4 on 2023-08-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_users_delete_user_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
