# Generated by Django 4.2.4 on 2023-08-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0005_alter_product_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('roll_no', models.IntegerField(max_length=255)),
                ('subject_name', models.CharField(max_length=255)),
            ],
        ),
    ]
