# Generated by Django 4.2.4 on 2023-08-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0007_alter_student_roll_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='aims_product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=250)),
                ('mh', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('branch_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('manufacture_id', models.IntegerField()),
                ('manufacture_name', models.CharField(max_length=250)),
                ('group_id', models.IntegerField()),
                ('sub_category_id', models.IntegerField()),
                ('group_name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=150)),
                ('bar_code', models.CharField(max_length=150)),
                ('rack', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('name_urdu', models.TextField(max_length=150)),
                ('pack', models.IntegerField()),
                ('pack_qty', models.IntegerField()),
                ('packing', models.TextField()),
                ('tp', models.FloatField()),
                ('tp2', models.FloatField()),
                ('tp3', models.FloatField()),
                ('final_price', models.FloatField()),
                ('rp', models.FloatField()),
                ('nrv', models.FloatField()),
                ('gst_percent', models.FloatField()),
                ('gst_amount', models.FloatField()),
                ('un_reg_gst_percent', models.FloatField()),
                ('un_reg_gst_amount', models.FloatField()),
                ('tax_after_disc', models.CharField(max_length=250)),
                ('weight_value', models.FloatField()),
                ('stock_limit', models.IntegerField()),
                ('distibuter_discount', models.FloatField()),
                ('customer_discount', models.FloatField()),
                ('item_unit', models.CharField(max_length=150)),
                ('detail', models.CharField(max_length=150)),
                ('image', models.TextField()),
                ('qty', models.FloatField()),
                ('qty_log', models.FloatField()),
                ('qty_on_bonus', models.FloatField()),
                ('bonus', models.FloatField()),
                ('status', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
