# Generated by Django 4.2.4 on 2023-08-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0008_aims_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aims_product',
            name='deleted_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='aims_product',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
