# Generated by Django 4.2.4 on 2023-08-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0009_alter_aims_product_deleted_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aims_product',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
