# Generated by Django 4.2.4 on 2023-08-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0010_alter_aims_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='aims_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('user_type', models.CharField(max_length=150)),
                ('full_name', models.CharField(max_length=150)),
                ('l_name', models.CharField(max_length=150)),
                ('user_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('passs', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('is_super_user', models.IntegerField()),
                ('old_status', models.CharField(max_length=50)),
                ('is_price_change', models.IntegerField()),
                ('is_discount', models.IntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
