# Generated by Django 4.2.4 on 2023-08-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0011_aims_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aims_product',
            name='image',
            field=models.CharField(max_length=150),
        ),
    ]
