# Generated by Django 4.2.5 on 2023-09-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0017_doctor_delete_aims_product_delete_aims_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
