# Generated by Django 4.2.5 on 2023-09-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0021_inventory_staff_remove_patient_medical_history_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Billing',
        ),
    ]
