# Generated by Django 4.2.5 on 2023-09-25 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0022_delete_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('invoice_date', models.DateField()),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings_with_item_name', to='api_v1.inventory', verbose_name='item name')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.patient')),
            ],
        ),
    ]
